server:
  port: ${PORT:8762}

eureka:
  ###集群环境下 需要配置client 作为一个clent去注册
  client:
    serviceUrl:
      # 需要注册到的eureka服务节点
      defaultZone: http://${EUREKA_USER:fnb}:${EUREKA_PWD:fnb2019}@${EUREKA1_SERVICE_HOST:localhost}:${EUREKA1_SERVICE_PORT:8761}/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: 注册中心2(${spring.cloud.client.ip-address}:${server.port})
  server:
    ####本地测试环境时 关闭自我保护机制,保证不可用服务及时踢出 默认为true
    enable-self-preservation: false
    ###清理间隔 单位毫秒,默认是90秒
    eviction-interval-timer-in-ms: 10000
    peer-node-connect-timeout-ms: 3000
    peer-node-read-timeout-ms: 3000
#  server:
#    ####本地测试环境时 关闭自我保护机制,保证不可用服务及时踢出 默认为true
#    enable-self-preservation: false
#    ###清理间隔 单位毫秒,默认是90秒
#    eviction-interval-timer-in-ms: 10000